site_name: Akihiro Hayashi
site_url: https://ahayashi.github.io/
repo_name: ahayashi
repo_url: https://github.com/ahayashi/ahayashi.github.io/
edit_uri: blob/mkdocs/docs/
docs_dir: docs

theme:
  name: material
  features:
    - content.action.edit

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Inconsolata
  palette:
    primary: black
    scheme: slate
  favicon: material/alpha-a-box
  icon:
    logo: material/alpha-a-box

nav:
    - Home: index.md
    - Education: education.md
    - Professional Experience: professional_experience.md
    - Professional Committees: professional_committees.md
    - Publications: publications.md
    - Projects: projects.md
    - CV: cv.md

